const AUDIT_ACTIONS = Object.freeze({
  BEGINNER_GUIDE_REWARD_GRANT: "beginner_guide_reward_grant",
  RECHARGE_CONFIG_UPDATE: "recharge_config_update",
  HELPER_INVENTORY_PRUNE: "helper_inventory_prune",
  LINEUP_SLOT_PURCHASE: "lineup_slot_purchase",
  EXTERNAL_ORDER_CREATE: "external_order_create",
  CARDS_IMPORT: "cards_import",
  PRODUCT_UPDATE: "product_update",
  PRODUCT_STATUS_UPDATE: "product_status_update",
  BUNDLE_UPDATE: "bundle_update",
  BUNDLE_STATUS_UPDATE: "bundle_status_update",
  PRODUCT_BULK_STATUS_UPDATE: "product_bulk_status_update",
  PRODUCT_BULK_UPDATE: "product_bulk_update",
  USER_QUOTA_CHANGE: "user_quota_change",
  USER_HELPER_CAPABILITIES_UPDATE: "user_helper_capabilities_update",
  RECHARGE_ORDER_CREATE: "recharge_order_create",
  DRAW_SERVICE_ORDER_CREATE: "draw_service_order_create",
  RECHARGE_ORDER_REVIEW: "recharge_order_review",
  USER_STATUS_UPDATE: "user_status_update",
  ORDER_CREATE: "order_create",
  GUEST_TRANSFER_ORDER_CREATE: "guest_transfer_order_create",
  ORDER_CANCEL_REQUEST: "order_cancel_request",
  ORDER_STATUS_UPDATE: "order_status_update",
  ORDER_REMARK_UPDATE: "order_remark_update",
  PRODUCT_MANUAL_PRICE_CLEAR: "product_manual_price_clear",
  PRODUCT_PRICING_RECALCULATE: "product_pricing_recalculate",
  AUCTION_CREATE: "auction_create",
  AUCTION_BID_CREATE: "auction_bid_create",
  AUCTION_SETTLE: "auction_settle",
  AUCTION_CANCEL: "auction_cancel",
});

module.exports = {
  AUDIT_ACTIONS,
};
